Release announcement for cargo-audit v0.18
rust-lang/blog.rust-lang.org pull request #1139
Opened 2023-08-31 17:05 UTC by Shnatsel

2023-08-31 17:34 UTC, thomcc commented
This is a third party crate, no? It's a great tool, but I'm not sure why the update would be discussed on this blog.

2023-08-31 17:38 UTC, Shnatsel commented
This blog is also meant for Rust WGs to publish updates on their work, according to the README. This tool is maintained by an official WG.

Previous updates on this tool have also been published on this blog, e.g. https://github.com/rust-lang/blog.rust-lang.org/blob/master/posts/inside-rust/2019-10-03-Keeping-secure-with-cargo-audit-0.9.md

2023-08-31 18:10 UTC, thomcc commented
Hm, fair enough.

2023-09-01 19:57 UTC, Shnatsel commented
I see this has not been reviewed/merged in 2 days. I don't have the necessary permissions on this repo to assign reviewers. Is there anyone in particular I should reach out to in order to get this reviewed and merged?

2023-09-01 20:10 UTC, calebzulawski requested changes

2023-09-01 20:10 UTC, calebzulawski commented on posts/2023-08-29-keeping-secure-with-cargo-audit-0.18.md
> +Both `cargo audit` and the [RustSec](https://rustsec.org/) advisory database that powers it are maintaiend by the [Rust Secure Code working group](https://www.rust-lang.org/governance/wgs/wg-secure-c
Typo

2023-09-01 20:15 UTC, calebzulawski approved these changes

2023-09-01 20:17 UTC, calebzulawski commented
Apparently I could fix that typo from the mobile website :) Looks good to me, I'll leave the merge up to you

2023-09-01 20:21 UTC, Shnatsel commented
Thanks for the quick review!

2023-09-02 08:41 UTC, Shnatsel commented
@thomcc I moved the post to inside-rust. It was meant to go there, I put it on the main blog by mistake.

2023-09-04 13:35 UTC, Shnatsel commented
I need this to go live, but I don't have permission to merge it.

Could someone please push the button? :sweat_smile:

2023-09-04 13:49 UTC, merged

2023-09-04 14:30 UTC, Shnatsel commented
Thank you! :heart: