Inside Rust: March CTCFT agenda
rust-lang/blog.rust-lang.org pull request #950
Opened 2022-03-15 18:20 UTC by AngelOnFira

2022-03-15 19:13 UTC, nikomatsakis requested changes

2022-03-15 19:34 UTC, nikomatsakis submitted a review, later dismissed

2022-03-15 19:34 UTC, nikomatsakis commented on posts/inside-rust/2022-03-15-CTCFT-march.md
> +- (5 min) Opening remarks 👋 ([Rebecca Rumbul])
```suggestion
- (5 min) Opening remarks 👋
```

2022-03-15 22:07 UTC, nikomatsakis commented
@rust-lang/core can we get someone to merge this? it's somewhat time sensitive :)

2022-03-16 09:09 UTC, badboy approved these changes

2022-03-16 09:10 UTC, merged