Add blog post about recent Clippy team changes
rust-lang/blog.rust-lang.org pull request #999
Opened 2022-06-30 12:28 UTC by flip1995

We changed the Clippy team quite a bit recently with 3 new team additions. We want to get this a little bit more visibility and decided to write up a blog post, like other teams do.

cc @rust-lang/clippy

2022-06-30 16:28 UTC, AngelOnFira commented on posts/inside-rust/2022-06-30-clippy-team-changes.md
> +deserved alumni status. We want to thank [Pascal
```suggestion
At the same time, we recently granted some of our oldest members the
well-deserved alumni status. We want to thank [Pascal
```

2022-06-30 16:33 UTC, Manishearth approved these changes
r? @rylev

2022-06-30 16:39 UTC, AngelOnFira commented on posts/inside-rust/2022-06-30-clippy-team-changes.md
> +them!
I think this paragraph is a bit confusing. I think this conveys the same intention, but might still need some work.

```suggestion
And finally, thank you to [mikerite](https://github.com/mikerite), who will
be stepping down from an active reviewer/team member position, but will
be staying on as a contributor. We're looking forward to continue working
with them!
```

2022-07-01 13:02 UTC, rylev requested changes
Looks great! We might have another post in the docket for today (though on the main blog and not the inside-rust blog). We may want to hold off until 04-July to post. In the meantime, there's a few nits to sort through.

2022-07-01 13:06 UTC, flip1995 commented
Just noticed that this is PR #999. Sooo close :smiling_face_with_tear:

2022-07-11 13:21 UTC, rylev commented
@flip1995 sorry for the delay - I was on holiday last week. Does tomorrow (2022-07-12) work?

2022-07-11 14:00 UTC, flip1995 commented
Works for me. I squashed+rebased the post and updated the date to tomorrow :+1:

2022-07-13 07:55 UTC, flip1995 commented
ping @rylev bumped the date to today. Yesterday this would've interfered with the core team update. I would like to get this merged rather sooner than later now.

2022-07-13 09:35 UTC, rylev approved these changes

2022-07-13 13:25 UTC, merged

2022-07-13 13:25 UTC, rylev commented
@flip1995 it has been merged! Thanks for your patience!